apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vega-ops-bench
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: vega-ops-bench.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vega-ops-bench
                port:
                  number: 80
