apiVersion: v1
kind: Service
metadata:
  name: vega-ops-bench
  labels:
    app: vega-ops-bench
spec:
  type: ClusterIP
  selector:
    app: vega-ops-bench
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
